// SPDX-License-Identifier: Apache-2.0
/** Writes docs/compatibility.md from tests/corpus/results.json (the recorded, regression-checked results). */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { CorpusResults } from "../tests/corpus/corpus-lib.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const r = JSON.parse(readFileSync(join(root, "tests", "corpus", "results.json"), "utf8")) as CorpusResults;
const lines = [
  "<!-- Generated by `npm run docs:compat` from tests/corpus/results.json. Do not edit by hand. -->",
  "",
  "# Compatibility: buildingSMART Certification-datasets",
  "",
  `Every IFC file of [${r.repository}](${r.repository}) at commit \`${r.commit}\` is part of the mandatory test suite.`,
  "The dataset (CC BY 4.0, © buildingSMART International Ltd.) is fetched by `npm run corpus:fetch`; it is not redistributed with this project.",
  "",
  "Two suites run every file, and neither skips files or accepts expected failures:",
  "",
  "- `npm run test:corpus` (Node): the full pipeline (stream parse, IFC model, geometry, GPU packing). A file passes when it loads without error diagnostics, every product with a representation produces geometry, all emitted buffers are finite and in range, and the numbers below match (regression check).",
  "- `npm run test:corpus:browser` (Chromium): each file is opened in the real `<ifc-viewer>` (worker, WebGL renderer, UI). The results must equal the Node results, there must be no fatal errors or page errors, the fitted model must be visible, and every product, isolated and framed on its own, must draw pixels.",
  "",
  `**${r.files.length} / ${r.files.length} files pass.**`,
  "",
  "| File | Schema | Entities | Products | Displayed | Triangles | Warnings |",
  "|---|---|---:|---:|---:|---:|---:|",
  ...r.files.map((f) => `| ${f.path} | ${f.schema} | ${f.entities} | ${f.products} | ${f.productsWithGeometry} / ${f.geometryProducts} | ${f.triangles} | ${f.warningDiagnostics} |`),
  "",
  "*Displayed* counts products with a body (or curve) representation that produced geometry, out of those that have one. Products without any representation (e.g. an empty IfcBuilding) appear in the spatial tree only.",
  "",
];
writeFileSync(join(root, "docs", "compatibility.md"), lines.join("\n"));
console.log("docs/compatibility.md updated");
