// SPDX-License-Identifier: Apache-2.0
/**
 * Writes docs/api.md from the compiler-emitted declaration files (dist/*.d.ts),
 * so the documented public interfaces are the real ones, verbatim.
 * Requires `npm run build`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dts = (file: string): string => readFileSync(join(root, "dist", file), "utf8");

/** Extracts one exported declaration (interface/type/class) by name. */
function declaration(source: string, name: string): string {
  const re = new RegExp(`^(\\/\\*\\*(?:(?!\\*\\/)[\\s\\S])*\\*\\/\\n)?export (declare )?(interface|type|class|const|function) ${name}\\b`, "m");
  const m = re.exec(source);
  if (!m) throw new Error(`declaration ${name} not found`);
  let i = m.index + m[0].length;
  let depth = 0;
  let seenBrace = false;
  for (; i < source.length; i++) {
    const c = source[i];
    if (c === "{" || c === "(") { depth++; seenBrace = true; }
    else if (c === "}" || c === ")") depth--;
    else if (c === ";" && depth === 0) { i++; break; }
    if (seenBrace && depth === 0 && c === "}") {
      i++;
      if (source[i] === ";") i++;
      break;
    }
  }
  const lines: string[] = [];
  for (const line of source.slice(m.index, i).split("\n")) {
    if (/^\s+private\b/.test(line)) {
      // drop the private member and its one-line doc comment
      if (lines.length && /^\s+\/\*\*.*\*\/\s*$/.test(lines[lines.length - 1]!)) lines.pop();
      continue;
    }
    lines.push(line);
  }
  return lines.join("\n").trim();
}

const viewer = dts("core/viewer.d.ts");
const element = dts("element/ifc-viewer-element.d.ts");
const protocol = dts("protocol/messages.d.ts");
const diagnostics = dts("diagnostics.d.ts");
const properties = dts("ifc/properties.d.ts");
const model = dts("ifc/model.d.ts");
const camera = dts("renderer/camera.d.ts");
const bridge = dts("iframe/client.d.ts");
const protocolBridge = dts("iframe/protocol.d.ts");

const block = (code: string): string => "```ts\n" + code + "\n```\n";
const section = (title: string, intro: string, decls: string[]): string => `## ${title}\n\n${intro}\n\n${block(decls.join("\n\n"))}`;

const out = [
  "<!-- Generated by `npm run docs:api` from the compiler's declaration output. Do not edit by hand. -->",
  "",
  "# API reference",
  "",
  "The package exposes three layers:",
  "",
  "- `<ifc-viewer>`: the custom element (entry `ifc-lens/element`, file `dist/ifc-viewer.js`).",
  "- `IfcViewer`: the renderer-level API used by the element, usable with your own canvas and UI.",
  "- The headless core (entry `ifc-lens/core`): STEP parser, IFC model and geometry engine for workers and Node.",
  "",
  section("Custom element", "`<ifc-viewer>` observes the attributes `src`, `ui` (`full` | `minimal` | `none`), `theme` (`light` | `dark` | `auto`), `autofit` (`false` disables fitting on load), `credentials` (`same-origin` | `include` | `omit`), `render-backend` (`webgl2`) and `worker-url`. All events bubble and are composed.", [
    declaration(element, "IfcViewerElement"),
    declaration(element, "defineIfcViewer"),
  ]),
  section("Viewer", "One `IfcViewer` owns one WebGL2 renderer, one model worker and the selection/visibility/clipping state of one model.", [
    declaration(viewer, "IfcViewer"),
    declaration(viewer, "ViewerOptions"),
    declaration(viewer, "IfcSource"),
    declaration(viewer, "LoadOptions"),
    declaration(protocol, "WorkerLimits"),
    declaration(viewer, "ModelHandle"),
    declaration(viewer, "SelectOptions"),
    declaration(viewer, "FitOptions"),
    declaration(viewer, "ClipPlane"),
    declaration(camera, "CameraState"),
  ]),
  section("Events", "Dispatched by `IfcViewer` and re-dispatched by `<ifc-viewer>` (bubbling, composed).", [
    declaration(viewer, "IfcViewerEventMap"),
    declaration(protocol, "LoadPhase"),
    declaration(protocol, "LoadStats"),
    declaration(diagnostics, "IfcDiagnostic"),
    declaration(diagnostics, "DiagnosticCode"),
    declaration(diagnostics, "ResourceLimitDetail"),
    declaration(diagnostics, "ResourceKind"),
  ]),
  section("Model data", "Returned by the model queries.", [
    declaration(protocol, "ModelMetadata"),
    declaration(protocol, "TreeNodeWire"),
    declaration(properties, "PropertyGroup"),
    declaration(properties, "PropertyValue"),
    declaration(model, "EntitySummary"),
  ]),
  section("Iframe bridge", "Host-page client for a viewer embedded in a (possibly cross-origin) iframe; see docs/embedding.md.", [
    declaration(bridge, "IfcViewerFrameClient"),
    declaration(bridge, "FrameClientOptions"),
    declaration(protocolBridge, "BridgeEnvelope"),
    declaration(protocolBridge, "BridgeCommand"),
  ]),
].join("\n");

writeFileSync(join(root, "docs", "api.md"), out);
console.log("docs/api.md updated");
