// SPDX-License-Identifier: Apache-2.0
/** Renders docs/ifc-support.md from the machine-readable support matrix. */
import type { IfcSupportEntry } from "../src/ifc/support.ts";

const LABEL: Record<string, string> = { full: "Full", partial: "Partial", none: "No", "n/a": "—" };
const CATEGORY_TITLES: Record<IfcSupportEntry["category"], string> = {
  placement: "Placements and coordinate systems",
  instancing: "Instancing",
  profile: "Profiles",
  curve: "Curves",
  solid: "Swept and primitive solids",
  boolean: "Booleans and clipping",
  semantic: "Semantic geometry",
  tessellation: "Tessellated geometry",
  brep: "Boundary representations",
  surface: "Surfaces",
  presentation: "Presentation",
};

export function renderSupportMarkdown(matrix: readonly IfcSupportEntry[]): string {
  const lines: string[] = [
    "<!-- Generated by `npm run docs:support` from src/ifc/support.ts. Do not edit by hand. -->",
    "",
    "# IFC support matrix",
    "",
    "Support levels per schema family. **Full** means the entity is interpreted according to the specification;",
    "**Partial** lists the limitations; **No** means the item is reported as `GEOMETRY_UNSUPPORTED` for that product",
    "while the rest of the model keeps loading; **—** means the entity does not exist in that schema.",
    "",
    "The table is enforced by `tests/unit/support-matrix.test.ts`: every representation item marked as supported",
    "must be handled by the geometry dispatcher.",
    "",
  ];
  const order = Object.keys(CATEGORY_TITLES) as IfcSupportEntry["category"][];
  for (const category of order) {
    const entries = matrix.filter((e) => e.category === category);
    if (entries.length === 0) continue;
    lines.push(`## ${CATEGORY_TITLES[category]}`, "", "| Entity | IFC2X3 | IFC4 | IFC4X3 | Phase | Limitations |", "|---|---|---|---|---|---|");
    for (const e of entries) {
      lines.push(`| ${e.entity} | ${LABEL[e.ifc2x3]} | ${LABEL[e.ifc4]} | ${LABEL[e.ifc4x3]} | ${e.phase} | ${(e.limitations ?? []).join("; ") || ""} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
